-- 승인/반려 관리 DDL/DML/운영분석 SQL
-- 대표 테이블: TBAPPROVAL, snapshot 컬럼: APPROVERNM

CREATE TABLE TBAPPROVAL (
    ID              VARCHAR(40)   NOT NULL,
    INSTCD          VARCHAR(20)   NOT NULL,
    USERID          VARCHAR(40),
    NAME            VARCHAR(100),
    APPROVERNM      VARCHAR(100),
    STATUS          VARCHAR(20),
    CREATED_BY      VARCHAR(40),
    UPDATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    REVISION        INTEGER,
    CONSTRAINT PK_TBAPPROVAL PRIMARY KEY (ID)
);

CREATE INDEX IX_TBAPPROVAL_INSTCD ON TBAPPROVAL(INSTCD);
CREATE INDEX IX_TBAPPROVAL_STATUS ON TBAPPROVAL(STATUS);
CREATE INDEX IX_TBAPPROVAL_MISMATCH ON TBAPPROVAL(INSTCD, STATUS, NAME, APPROVERNM);

INSERT INTO TBAPPROVAL VALUES ('APPROVAL001','INST001','U001','김담당','김담당','SUBMITTED','SYSTEM','SYSTEM',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);
INSERT INTO TBAPPROVAL VALUES ('APPROVAL002','INST002','U002','이담당','이전담당','SUBMITTED','SYSTEM','BATCH',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,2);
INSERT INTO TBAPPROVAL VALUES ('APPROVAL003','INST003','U003','박담당','박담당','READY','SYSTEM','SYSTEM',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);

-- 제출완료 기관 중 현재명과 snapshot명이 다른 건 추출
SELECT INSTCD, USERID, NAME AS CURRENT_NAME, APPROVERNM AS SNAPSHOT_NAME, STATUS
  FROM TBAPPROVAL
 WHERE STATUS = 'SUBMITTED'
   AND NVL(NAME, ' ') <> NVL(APPROVERNM, ' ');

-- TBUSER와의 비교. 운영 문의 예시에서 가장 자주 쓰는 형태.
SELECT A.INSTCD, U.USERNM, A.APPROVERNM, A.STATUS, A.UPDATED_AT
  FROM TBAPPROVAL A
  JOIN TBUSER U
    ON A.INSTCD = U.INSTCD
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(U.USERNM, ' ') <> NVL(A.APPROVERNM, ' ');

-- 분석 SQL 1: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 2: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 3: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 4: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 5: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 6: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 7: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 8: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 9: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 10: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 11: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 12: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 13: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 14: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 15: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 16: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 17: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 18: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 19: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.APPROVERNM, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBAPPROVAL A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.APPROVERNM, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;
