-- 감사 이력 Tibero 운영 분석 SQL
-- 테이블: TBAUDITHIST, 비교 컬럼: ACTIONUSERNM
-- 서브쿼리를 쓰지 않고 JOIN과 조건 분해로 확인한다.

CREATE TABLE TBAUDITHIST (
    ID              VARCHAR(40)    NOT NULL,
    INSTCD          VARCHAR(20)    NOT NULL,
    USERID          VARCHAR(40),
    ACTIONUSERNM    VARCHAR(100),
    STATUS          VARCHAR(20),
    SUBMIT_DT       DATE,
    CHANGE_DT       DATE,
    BATCH_YN        CHAR(1),
    SKIP_REASON     VARCHAR(200),
    SOURCE_REVISION VARCHAR(40),
    SCREEN_ID       VARCHAR(80),
    TRANSACTION_ID  VARCHAR(80),
    UPDATED_BY      VARCHAR(40),
    MEMO            VARCHAR(500),
    CONSTRAINT PK_TBAUDITHIST PRIMARY KEY (ID)
);

CREATE INDEX IX_TBAUDITHIST_01 ON TBAUDITHIST(INSTCD, STATUS);
CREATE INDEX IX_TBAUDITHIST_02 ON TBAUDITHIST(TRANSACTION_ID, SCREEN_ID);
CREATE INDEX IX_TBAUDITHIST_03 ON TBAUDITHIST(SOURCE_REVISION, CHANGE_DT);

INSERT INTO TBAUDITHIST VALUES ('AUDIT_HISTORY001','INST001','U001','김담당','SUBMITTED', DATE '2026-05-15', DATE '2026-05-18','N','담당자 개별 수정','r20260518','감사로그조회','audit_history_change','admin','작업자명 변경 후 과거 감사 로그에는 당시 이름이 남는 상황');
INSERT INTO TBAUDITHIST VALUES ('AUDIT_HISTORY002','INST002','U002','이전담당','SUBMITTED', DATE '2026-05-15', DATE '2026-05-19','Y',NULL,'r20260519','감사로그조회','audit_history_submit','batch','정상 snapshot 보존');
INSERT INTO TBAUDITHIST VALUES ('AUDIT_HISTORY003','INST003','U003','박담당','READY', DATE '2026-05-16', DATE '2026-05-16','N','미제출','r20260516','감사로그조회','audit_history_search','system','분석 제외 후보');

-- 1단계: 제출완료 데이터만 확인
SELECT A.INSTCD, A.ID, A.ACTIONUSERNM, A.STATUS, A.SUBMIT_DT, A.CHANGE_DT
  FROM TBAUDITHIST A
 WHERE A.STATUS = 'SUBMITTED'
 ORDER BY A.INSTCD;

-- 2단계: TBUSER 현재 담당자명과 snapshot 값을 JOIN으로 비교
SELECT A.INSTCD, U.USERNM, A.ACTIONUSERNM AS SNAPSHOT_VALUE, A.STATUS, A.SOURCE_REVISION
  FROM TBAUDITHIST A
  JOIN TBUSER U
    ON A.INSTCD = U.INSTCD
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.INSTCD;

-- 3단계: 변경 이력과 연결
SELECT A.INSTCD, U.USERNM, A.ACTIONUSERNM, H.CHANGEDESC, H.CREATED_AT
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBHISTORY H ON A.ID = H.TARGET_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 진단 SQL 1: 감사로그조회 / 운영자 작업 기록 / trace 1
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_1'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 2: 감사로그조회 / 운영자 작업 기록 / trace 2
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_2'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 3: 감사로그조회 / 운영자 작업 기록 / trace 3
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_3'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 4: 감사로그조회 / 운영자 작업 기록 / trace 4
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_4'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 5: 감사로그조회 / 운영자 작업 기록 / trace 5
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_5'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 6: 감사로그조회 / 운영자 작업 기록 / trace 6
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_6'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 7: 감사로그조회 / 운영자 작업 기록 / trace 7
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_7'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 8: 감사로그조회 / 운영자 작업 기록 / trace 8
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_8'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 9: 감사로그조회 / 운영자 작업 기록 / trace 9
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_9'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 10: 감사로그조회 / 운영자 작업 기록 / trace 10
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_10'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 11: 감사로그조회 / 운영자 작업 기록 / trace 11
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_11'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 12: 감사로그조회 / 운영자 작업 기록 / trace 12
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_12'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 13: 감사로그조회 / 운영자 작업 기록 / trace 13
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_13'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 14: 감사로그조회 / 운영자 작업 기록 / trace 14
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_14'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 15: 감사로그조회 / 운영자 작업 기록 / trace 15
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_15'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 16: 감사로그조회 / 운영자 작업 기록 / trace 16
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_16'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 17: 감사로그조회 / 운영자 작업 기록 / trace 17
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_17'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 18: 감사로그조회 / 운영자 작업 기록 / trace 18
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_18'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 19: 감사로그조회 / 운영자 작업 기록 / trace 19
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_19'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 20: 감사로그조회 / 운영자 작업 기록 / trace 20
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_20'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 21: 감사로그조회 / 운영자 작업 기록 / trace 21
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_21'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 22: 감사로그조회 / 운영자 작업 기록 / trace 22
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_22'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 23: 감사로그조회 / 운영자 작업 기록 / trace 23
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_23'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 24: 감사로그조회 / 운영자 작업 기록 / trace 24
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_24'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 25: 감사로그조회 / 운영자 작업 기록 / trace 25
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_25'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 26: 감사로그조회 / 운영자 작업 기록 / trace 26
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_26'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 27: 감사로그조회 / 운영자 작업 기록 / trace 27
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.ACTIONUSERNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBAUDITHIST A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'audit_history_tx_27'
   AND NVL(U.USERNM, ' ') <> NVL(A.ACTIONUSERNM, ' ')
 ORDER BY A.CHANGE_DT DESC;
