-- 데이터 불일치 분석 DDL/DML/운영분석 SQL
-- 대표 테이블: TBDISCREPANCY, snapshot 컬럼: REASON

CREATE TABLE TBDISCREPANCY (
    ID              VARCHAR(40)   NOT NULL,
    INSTCD          VARCHAR(20)   NOT NULL,
    USERID          VARCHAR(40),
    NAME            VARCHAR(100),
    REASON          VARCHAR(100),
    STATUS          VARCHAR(20),
    CREATED_BY      VARCHAR(40),
    UPDATED_BY      VARCHAR(40),
    CREATED_AT      TIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    REVISION        INTEGER,
    CONSTRAINT PK_TBDISCREPANCY PRIMARY KEY (ID)
);

CREATE INDEX IX_TBDISCREPANCY_INSTCD ON TBDISCREPANCY(INSTCD);
CREATE INDEX IX_TBDISCREPANCY_STATUS ON TBDISCREPANCY(STATUS);
CREATE INDEX IX_TBDISCREPANCY_MISMATCH ON TBDISCREPANCY(INSTCD, STATUS, NAME, REASON);

INSERT INTO TBDISCREPANCY VALUES ('DISCREPANCY001','INST001','U001','김담당','김담당','SUBMITTED','SYSTEM','SYSTEM',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);
INSERT INTO TBDISCREPANCY VALUES ('DISCREPANCY002','INST002','U002','이담당','이전담당','SUBMITTED','SYSTEM','BATCH',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,2);
INSERT INTO TBDISCREPANCY VALUES ('DISCREPANCY003','INST003','U003','박담당','박담당','READY','SYSTEM','SYSTEM',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,1);

-- 제출완료 기관 중 현재명과 snapshot명이 다른 건 추출
SELECT INSTCD, USERID, NAME AS CURRENT_NAME, REASON AS SNAPSHOT_NAME, STATUS
  FROM TBDISCREPANCY
 WHERE STATUS = 'SUBMITTED'
   AND NVL(NAME, ' ') <> NVL(REASON, ' ');

-- TBUSER와의 비교. 운영 문의 예시에서 가장 자주 쓰는 형태.
SELECT A.INSTCD, U.USERNM, A.REASON, A.STATUS, A.UPDATED_AT
  FROM TBDISCREPANCY A
  JOIN TBUSER U
    ON A.INSTCD = U.INSTCD
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(U.USERNM, ' ') <> NVL(A.REASON, ' ');

-- 분석 SQL 1: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 2: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 3: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 4: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 5: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 6: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 7: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 8: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 9: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 10: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 11: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 12: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 13: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 14: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 15: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 16: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 17: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 18: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 분석 SQL 19: 특정 기관 기준 불일치 및 변경 이력 추적
SELECT A.INSTCD, A.ID, A.NAME, A.REASON, A.STATUS, A.UPDATED_BY, A.UPDATED_AT,
       H.CHANGEDESC, H.CREATED_AT AS HISTORY_AT
  FROM TBDISCREPANCY A
  LEFT JOIN TBHISTORY H
    ON A.ID = H.ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(A.NAME, ' ') <> NVL(A.REASON, ' ')
   AND A.INSTCD IN ('INST001','INST002','INST003','INST004')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;
