-- 조사 마스터 Tibero 운영 분석 SQL
-- 테이블: TBSURVEY, 비교 컬럼: SURVEYNM
-- 서브쿼리를 쓰지 않고 JOIN과 조건 분해로 확인한다.

CREATE TABLE TBSURVEY (
    ID              VARCHAR(40)    NOT NULL,
    INSTCD          VARCHAR(20)    NOT NULL,
    USERID          VARCHAR(40),
    SURVEYNM        VARCHAR(100),
    STATUS          VARCHAR(20),
    SUBMIT_DT       DATE,
    CHANGE_DT       DATE,
    BATCH_YN        CHAR(1),
    SKIP_REASON     VARCHAR(200),
    SOURCE_REVISION VARCHAR(40),
    SCREEN_ID       VARCHAR(80),
    TRANSACTION_ID  VARCHAR(80),
    UPDATED_BY      VARCHAR(40),
    MEMO            VARCHAR(500),
    CONSTRAINT PK_TBSURVEY PRIMARY KEY (ID)
);

CREATE INDEX IX_TBSURVEY_01 ON TBSURVEY(INSTCD, STATUS);
CREATE INDEX IX_TBSURVEY_02 ON TBSURVEY(TRANSACTION_ID, SCREEN_ID);
CREATE INDEX IX_TBSURVEY_03 ON TBSURVEY(SOURCE_REVISION, CHANGE_DT);

INSERT INTO TBSURVEY VALUES ('SURVEY_MASTER001','INST001','U001','김담당','SUBMITTED', DATE '2026-05-15', DATE '2026-05-18','N','담당자 개별 수정','r20260518','조사기본정보','survey_master_change','admin','조사명 변경 후 기존 제출 이력의 조사명이 과거 값으로 보이는 상황');
INSERT INTO TBSURVEY VALUES ('SURVEY_MASTER002','INST002','U002','이전담당','SUBMITTED', DATE '2026-05-15', DATE '2026-05-19','Y',NULL,'r20260519','조사기본정보','survey_master_submit','batch','정상 snapshot 보존');
INSERT INTO TBSURVEY VALUES ('SURVEY_MASTER003','INST003','U003','박담당','READY', DATE '2026-05-16', DATE '2026-05-16','N','미제출','r20260516','조사기본정보','survey_master_search','system','분석 제외 후보');

-- 1단계: 제출완료 데이터만 확인
SELECT A.INSTCD, A.ID, A.SURVEYNM, A.STATUS, A.SUBMIT_DT, A.CHANGE_DT
  FROM TBSURVEY A
 WHERE A.STATUS = 'SUBMITTED'
 ORDER BY A.INSTCD;

-- 2단계: TBUSER 현재 담당자명과 snapshot 값을 JOIN으로 비교
SELECT A.INSTCD, U.USERNM, A.SURVEYNM AS SNAPSHOT_VALUE, A.STATUS, A.SOURCE_REVISION
  FROM TBSURVEY A
  JOIN TBUSER U
    ON A.INSTCD = U.INSTCD
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.INSTCD;

-- 3단계: 변경 이력과 연결
SELECT A.INSTCD, U.USERNM, A.SURVEYNM, H.CHANGEDESC, H.CREATED_AT
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBHISTORY H ON A.ID = H.TARGET_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 진단 SQL 1: 조사기본정보 / 조사 기본정보 수정 / trace 1
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_1'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 2: 조사기본정보 / 조사 기본정보 수정 / trace 2
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_2'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 3: 조사기본정보 / 조사 기본정보 수정 / trace 3
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_3'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 4: 조사기본정보 / 조사 기본정보 수정 / trace 4
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_4'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 5: 조사기본정보 / 조사 기본정보 수정 / trace 5
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_5'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 6: 조사기본정보 / 조사 기본정보 수정 / trace 6
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_6'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 7: 조사기본정보 / 조사 기본정보 수정 / trace 7
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_7'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 8: 조사기본정보 / 조사 기본정보 수정 / trace 8
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_8'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 9: 조사기본정보 / 조사 기본정보 수정 / trace 9
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_9'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 10: 조사기본정보 / 조사 기본정보 수정 / trace 10
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_10'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 11: 조사기본정보 / 조사 기본정보 수정 / trace 11
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_11'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 12: 조사기본정보 / 조사 기본정보 수정 / trace 12
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_12'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 13: 조사기본정보 / 조사 기본정보 수정 / trace 13
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_13'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 14: 조사기본정보 / 조사 기본정보 수정 / trace 14
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_14'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 15: 조사기본정보 / 조사 기본정보 수정 / trace 15
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_15'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 16: 조사기본정보 / 조사 기본정보 수정 / trace 16
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_16'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 17: 조사기본정보 / 조사 기본정보 수정 / trace 17
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_17'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 18: 조사기본정보 / 조사 기본정보 수정 / trace 18
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_18'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 19: 조사기본정보 / 조사 기본정보 수정 / trace 19
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_19'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 20: 조사기본정보 / 조사 기본정보 수정 / trace 20
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_20'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 21: 조사기본정보 / 조사 기본정보 수정 / trace 21
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_21'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 22: 조사기본정보 / 조사 기본정보 수정 / trace 22
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_22'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 23: 조사기본정보 / 조사 기본정보 수정 / trace 23
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_23'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 24: 조사기본정보 / 조사 기본정보 수정 / trace 24
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_24'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 25: 조사기본정보 / 조사 기본정보 수정 / trace 25
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_25'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 26: 조사기본정보 / 조사 기본정보 수정 / trace 26
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_26'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 27: 조사기본정보 / 조사 기본정보 수정 / trace 27
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.SURVEYNM AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBSURVEY A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'survey_master_tx_27'
   AND NVL(U.USERNM, ' ') <> NVL(A.SURVEYNM, ' ')
 ORDER BY A.CHANGE_DT DESC;
