-- DBeaver 운영 SQL Tibero 운영 분석 SQL
-- 테이블: TBQUERYBOOK, 비교 컬럼: QUERYTITLE
-- 서브쿼리를 쓰지 않고 JOIN과 조건 분해로 확인한다.

CREATE TABLE TBQUERYBOOK (
    ID              VARCHAR(40)    NOT NULL,
    INSTCD          VARCHAR(20)    NOT NULL,
    USERID          VARCHAR(40),
    QUERYTITLE      VARCHAR(100),
    STATUS          VARCHAR(20),
    SUBMIT_DT       DATE,
    CHANGE_DT       DATE,
    BATCH_YN        CHAR(1),
    SKIP_REASON     VARCHAR(200),
    SOURCE_REVISION VARCHAR(40),
    SCREEN_ID       VARCHAR(80),
    TRANSACTION_ID  VARCHAR(80),
    UPDATED_BY      VARCHAR(40),
    MEMO            VARCHAR(500),
    CONSTRAINT PK_TBQUERYBOOK PRIMARY KEY (ID)
);

CREATE INDEX IX_TBQUERYBOOK_01 ON TBQUERYBOOK(INSTCD, STATUS);
CREATE INDEX IX_TBQUERYBOOK_02 ON TBQUERYBOOK(TRANSACTION_ID, SCREEN_ID);
CREATE INDEX IX_TBQUERYBOOK_03 ON TBQUERYBOOK(SOURCE_REVISION, CHANGE_DT);

INSERT INTO TBQUERYBOOK VALUES ('DBEAVER_QUERY001','INST001','U001','김담당','SUBMITTED', DATE '2026-05-15', DATE '2026-05-18','N','담당자 개별 수정','r20260518','운영SQL관리','dbeaver_query_change','admin','운영자가 서브쿼리 없이 조인 기반 확인 SQL을 작성해야 하는 상황');
INSERT INTO TBQUERYBOOK VALUES ('DBEAVER_QUERY002','INST002','U002','이전담당','SUBMITTED', DATE '2026-05-15', DATE '2026-05-19','Y',NULL,'r20260519','운영SQL관리','dbeaver_query_submit','batch','정상 snapshot 보존');
INSERT INTO TBQUERYBOOK VALUES ('DBEAVER_QUERY003','INST003','U003','박담당','READY', DATE '2026-05-16', DATE '2026-05-16','N','미제출','r20260516','운영SQL관리','dbeaver_query_search','system','분석 제외 후보');

-- 1단계: 제출완료 데이터만 확인
SELECT A.INSTCD, A.ID, A.QUERYTITLE, A.STATUS, A.SUBMIT_DT, A.CHANGE_DT
  FROM TBQUERYBOOK A
 WHERE A.STATUS = 'SUBMITTED'
 ORDER BY A.INSTCD;

-- 2단계: TBUSER 현재 담당자명과 snapshot 값을 JOIN으로 비교
SELECT A.INSTCD, U.USERNM, A.QUERYTITLE AS SNAPSHOT_VALUE, A.STATUS, A.SOURCE_REVISION
  FROM TBQUERYBOOK A
  JOIN TBUSER U
    ON A.INSTCD = U.INSTCD
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.INSTCD;

-- 3단계: 변경 이력과 연결
SELECT A.INSTCD, U.USERNM, A.QUERYTITLE, H.CHANGEDESC, H.CREATED_AT
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBHISTORY H ON A.ID = H.TARGET_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 진단 SQL 1: 운영SQL관리 / 분석 SQL 실행 / trace 1
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_1'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 2: 운영SQL관리 / 분석 SQL 실행 / trace 2
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_2'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 3: 운영SQL관리 / 분석 SQL 실행 / trace 3
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_3'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 4: 운영SQL관리 / 분석 SQL 실행 / trace 4
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_4'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 5: 운영SQL관리 / 분석 SQL 실행 / trace 5
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_5'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 6: 운영SQL관리 / 분석 SQL 실행 / trace 6
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_6'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 7: 운영SQL관리 / 분석 SQL 실행 / trace 7
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_7'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 8: 운영SQL관리 / 분석 SQL 실행 / trace 8
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_8'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 9: 운영SQL관리 / 분석 SQL 실행 / trace 9
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_9'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 10: 운영SQL관리 / 분석 SQL 실행 / trace 10
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_10'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 11: 운영SQL관리 / 분석 SQL 실행 / trace 11
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_11'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 12: 운영SQL관리 / 분석 SQL 실행 / trace 12
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_12'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 13: 운영SQL관리 / 분석 SQL 실행 / trace 13
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_13'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 14: 운영SQL관리 / 분석 SQL 실행 / trace 14
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_14'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 15: 운영SQL관리 / 분석 SQL 실행 / trace 15
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_15'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 16: 운영SQL관리 / 분석 SQL 실행 / trace 16
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_16'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 17: 운영SQL관리 / 분석 SQL 실행 / trace 17
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_17'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 18: 운영SQL관리 / 분석 SQL 실행 / trace 18
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_18'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 19: 운영SQL관리 / 분석 SQL 실행 / trace 19
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_19'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 20: 운영SQL관리 / 분석 SQL 실행 / trace 20
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_20'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 21: 운영SQL관리 / 분석 SQL 실행 / trace 21
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_21'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 22: 운영SQL관리 / 분석 SQL 실행 / trace 22
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_22'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 23: 운영SQL관리 / 분석 SQL 실행 / trace 23
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_23'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 24: 운영SQL관리 / 분석 SQL 실행 / trace 24
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_24'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 25: 운영SQL관리 / 분석 SQL 실행 / trace 25
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_25'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 26: 운영SQL관리 / 분석 SQL 실행 / trace 26
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_26'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 27: 운영SQL관리 / 분석 SQL 실행 / trace 27
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.QUERYTITLE AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBQUERYBOOK A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'dbeaver_query_tx_27'
   AND NVL(U.USERNM, ' ') <> NVL(A.QUERYTITLE, ' ')
 ORDER BY A.CHANGE_DT DESC;
