-- Nexacro 라이선스 설정 Tibero 운영 분석 SQL
-- 테이블: TBCLIENTCONF, 비교 컬럼: LICENSEURL
-- 서브쿼리를 쓰지 않고 JOIN과 조건 분해로 확인한다.

CREATE TABLE TBCLIENTCONF (
    ID              VARCHAR(40)    NOT NULL,
    INSTCD          VARCHAR(20)    NOT NULL,
    USERID          VARCHAR(40),
    LICENSEURL      VARCHAR(100),
    STATUS          VARCHAR(20),
    SUBMIT_DT       DATE,
    CHANGE_DT       DATE,
    BATCH_YN        CHAR(1),
    SKIP_REASON     VARCHAR(200),
    SOURCE_REVISION VARCHAR(40),
    SCREEN_ID       VARCHAR(80),
    TRANSACTION_ID  VARCHAR(80),
    UPDATED_BY      VARCHAR(40),
    MEMO            VARCHAR(500),
    CONSTRAINT PK_TBCLIENTCONF PRIMARY KEY (ID)
);

CREATE INDEX IX_TBCLIENTCONF_01 ON TBCLIENTCONF(INSTCD, STATUS);
CREATE INDEX IX_TBCLIENTCONF_02 ON TBCLIENTCONF(TRANSACTION_ID, SCREEN_ID);
CREATE INDEX IX_TBCLIENTCONF_03 ON TBCLIENTCONF(SOURCE_REVISION, CHANGE_DT);

INSERT INTO TBCLIENTCONF VALUES ('NEXACRO_LICENSE001','INST001','U001','김담당','SUBMITTED', DATE '2026-05-15', DATE '2026-05-18','N','담당자 개별 수정','r20260518','클라이언트환경설정','nexacro_license_change','admin','launch.html에서 xadl licenseurl을 환경별로 바꾸는 상황');
INSERT INTO TBCLIENTCONF VALUES ('NEXACRO_LICENSE002','INST002','U002','이전담당','SUBMITTED', DATE '2026-05-15', DATE '2026-05-19','Y',NULL,'r20260519','클라이언트환경설정','nexacro_license_submit','batch','정상 snapshot 보존');
INSERT INTO TBCLIENTCONF VALUES ('NEXACRO_LICENSE003','INST003','U003','박담당','READY', DATE '2026-05-16', DATE '2026-05-16','N','미제출','r20260516','클라이언트환경설정','nexacro_license_search','system','분석 제외 후보');

-- 1단계: 제출완료 데이터만 확인
SELECT A.INSTCD, A.ID, A.LICENSEURL, A.STATUS, A.SUBMIT_DT, A.CHANGE_DT
  FROM TBCLIENTCONF A
 WHERE A.STATUS = 'SUBMITTED'
 ORDER BY A.INSTCD;

-- 2단계: TBUSER 현재 담당자명과 snapshot 값을 JOIN으로 비교
SELECT A.INSTCD, U.USERNM, A.LICENSEURL AS SNAPSHOT_VALUE, A.STATUS, A.SOURCE_REVISION
  FROM TBCLIENTCONF A
  JOIN TBUSER U
    ON A.INSTCD = U.INSTCD
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.INSTCD;

-- 3단계: 변경 이력과 연결
SELECT A.INSTCD, U.USERNM, A.LICENSEURL, H.CHANGEDESC, H.CREATED_AT
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBHISTORY H ON A.ID = H.TARGET_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.INSTCD, H.CREATED_AT DESC;

-- 진단 SQL 1: 클라이언트환경설정 / 라이선스 URL 변경 / trace 1
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_1'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 2: 클라이언트환경설정 / 라이선스 URL 변경 / trace 2
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_2'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 3: 클라이언트환경설정 / 라이선스 URL 변경 / trace 3
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_3'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 4: 클라이언트환경설정 / 라이선스 URL 변경 / trace 4
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_4'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 5: 클라이언트환경설정 / 라이선스 URL 변경 / trace 5
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_5'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 6: 클라이언트환경설정 / 라이선스 URL 변경 / trace 6
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_6'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 7: 클라이언트환경설정 / 라이선스 URL 변경 / trace 7
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_7'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 8: 클라이언트환경설정 / 라이선스 URL 변경 / trace 8
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_8'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 9: 클라이언트환경설정 / 라이선스 URL 변경 / trace 9
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_9'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 10: 클라이언트환경설정 / 라이선스 URL 변경 / trace 10
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_10'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 11: 클라이언트환경설정 / 라이선스 URL 변경 / trace 11
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_11'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 12: 클라이언트환경설정 / 라이선스 URL 변경 / trace 12
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_12'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 13: 클라이언트환경설정 / 라이선스 URL 변경 / trace 13
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_13'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 14: 클라이언트환경설정 / 라이선스 URL 변경 / trace 14
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_14'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 15: 클라이언트환경설정 / 라이선스 URL 변경 / trace 15
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_15'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 16: 클라이언트환경설정 / 라이선스 URL 변경 / trace 16
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_16'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 17: 클라이언트환경설정 / 라이선스 URL 변경 / trace 17
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_17'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 18: 클라이언트환경설정 / 라이선스 URL 변경 / trace 18
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_18'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 19: 클라이언트환경설정 / 라이선스 URL 변경 / trace 19
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_19'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 20: 클라이언트환경설정 / 라이선스 URL 변경 / trace 20
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_20'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 21: 클라이언트환경설정 / 라이선스 URL 변경 / trace 21
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_21'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 22: 클라이언트환경설정 / 라이선스 URL 변경 / trace 22
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_22'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 23: 클라이언트환경설정 / 라이선스 URL 변경 / trace 23
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_23'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 24: 클라이언트환경설정 / 라이선스 URL 변경 / trace 24
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_24'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 25: 클라이언트환경설정 / 라이선스 URL 변경 / trace 25
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_25'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 26: 클라이언트환경설정 / 라이선스 URL 변경 / trace 26
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_26'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;

-- 진단 SQL 27: 클라이언트환경설정 / 라이선스 URL 변경 / trace 27
SELECT A.INSTCD, A.ID, U.USERNM AS CURRENT_VALUE, A.LICENSEURL AS SAVED_VALUE,
       A.SUBMIT_DT, A.CHANGE_DT, A.BATCH_YN, A.SKIP_REASON, A.SOURCE_REVISION,
       A.SCREEN_ID, A.TRANSACTION_ID, A.UPDATED_BY
  FROM TBCLIENTCONF A
  JOIN TBUSER U ON A.INSTCD = U.INSTCD
  LEFT JOIN TBAI_OPERATOR_TRACE T ON A.SCREEN_ID = T.SCREEN_ID
 WHERE A.STATUS = 'SUBMITTED'
   AND A.TRANSACTION_ID = 'nexacro_license_tx_27'
   AND NVL(U.USERNM, ' ') <> NVL(A.LICENSEURL, ' ')
 ORDER BY A.CHANGE_DT DESC;
